services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest # or whatever version 
    container_name: mealie
    restart: unless-stopped 
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - ./data:/app/data/
      - ./ssl:/app/ssl/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      
      TZ: America/Los_Angeles # change this
      BASE_URL: https://whatever.com # change this
      
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
      
      #SMTP Settings
      SMTP_HOST: smtp-host.com # change this
      SMTP_PORT: 587 # change this
      SMTP_USER: smtp-username # change this
      SMTP_PASSWORD: smtp-password # change this
      SMTP_FROM_NAME: Our Recipe Server # change this if desired
      SMTP_FROM_EMAIL: recipes@whatever.com # change this
      SMTP_AUTH_STRATEGY: TLS # change this as needed
      
      #Mealie recipes server TLS Settings
      TLS_CERTIFICATE_PATH: /app/ssl/certificate.cer # change this as needed
      TLS_PRIVATE_KEY_PATH: /app/ssl/private.key # change this as needed

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - mealie-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mealie-data:
  mealie-pgdata:
